logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 1.15.185.99 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: itcast
    password: 123321
    virtual-host: /

#  application:
#    name: demoMongo
#  data:
#    mongodb:
#      host: mongo.zhledu.cn
#      database: g01
#      username: g01
#      password: abc@1
